name: PR Notification to Discord
on:
  pull_request:
    types: [opened, synchronize, reopened, closed, edited]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Notification to Discord
        uses: tsickert/discord-webhook@v5
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: GitHub Actions
          avatar-url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          embed-title: "PR Update: ${{ github.event.pull_request.title }}"
          embed-description: |
            **Action:** ${{ github.event.action }}
            **By:** ${{ github.event.pull_request.user.login }}
            [View PR](${{ github.event.pull_request.html_url }})
            **Status:** ${{ github.event.pull_request.state }}
          embed-color: "3447003"
